spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kihong
    password:
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
